### ISSUE TITLE
Amazon Smile in Incognito/Private Browsing

### ISSUE THREAD

**Issue by PseudoResonance** [eukaryote/amazonsmiley#1]
While this extension works really well, it would be great if the extension was disabled when the browser was in incognito or private browsing, as you can't navigate Amazon if you're not signed in.
Of course, I can see why this would not be ideal as well, as for most people, there's not much point in going to Amazon if they're not going to log in, so perhaps if there was a checkbox in the options or something that could turn the extension off automatically when the browser is in incognito/private mode.
Thanks!

**Comment by eukaryote** [comment]
Thanks for the suggestion. I added an option to support disabling the redirect behavior in incognito/private mode.

The option is named "Disable in Incognito/Private Mode", and if you check that option, it shouldn't interfere in incognito/private-mode windows. Open 'about:addons' in a new tab to get to the addons page, and if you're on version 1.8 of the plugin, or later you should see that option at the bottom.

**Comment by keeganwitt** [comment]
I don't understand what the impetus for this request was, Firefox has a built-in option to not allow extensions to run on private windows, and they are blocked by default.

![image](https://user-images.githubusercontent.com/64612/89737245-89eb9780-da3d-11ea-85bd-c7a2ed4b8384.png)

**Comment by PseudoResonance** [comment]
This option did not exist back when this issue was created.
